export const messages = [
    {
      id: 1,
      title: 'Brunch this week?',
      description: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      images: "RandeomUrl",
      statusmg: false,
    },
    {
      id: 2,
      title: 'Birthday Gift',
      description: `Do you have a suggestion for a good present for John on his work anniversary. I am really confused & would love your thoughts on it.`,
      images: "RandeomUrl",
      statusmg: true,
    },
    {
      id: 3,
      title: 'Recipe to try',
      description: 'I am try out this new BBQ recipe, I think this might be amazing',
      images: "RandeomUrl",
      statusmg: true,
    },
    {
      id: 4,
      title: 'Yes!',
      description: 'I have the tickets to the ReactConf for this year.',
      images: "RandeomUrl",
      statusmg:false,
    },
    {
      id: 5,
      title: "Doctor's Appointment",
      description: 'My appointment for the doctor was rescheduled for next Saturday.',
      images: "RandeomUrl",
      statusmg: true,
    },
    {
      id: 6,
      title: 'Discussion',
      description: `Menus that are generated by the bottom app bar (such as a bottom navigation drawer or overflow menu) open as bottom sheets at a higher elevation than the bar.`,
      images: "RandeomUrl",
      statusmg: false,
    },
    {
      id: 7,
      title: 'Summer BBQ',
      description: `Who wants to have a cookout this weekend? I just got some furniture for my backyard and would love to fire up the grill.`,
      images: "RandeomUrl",
      statusmg: true,
    },
  ];
  